# Фронтенд
FROM node:22-alpine AS builder

WORKDIR /app

# Копируем package.json (и package-lock.json если есть)
COPY package*.json ./
RUN npm install

COPY . .
# Увеличиваем память для сборки и ставим production режим
RUN NODE_OPTIONS="--max-old-space-size=1024" npm run build -- --mode production

# Продакшен образ
FROM nginx:alpine

# Копируем собранное приложение
COPY --from=builder /app/dist /usr/share/nginx/html

# Копируем кастомную nginx конфигурацию если нужно
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]