FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN NODE_OPTIONS="--max-old-space-size=1024" npm run build
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
# НЕ КОПИРУЕМ nginx.conf - он уже в главном nginx контейнере
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]