version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    nginx:
        image: nginx:stable
        container_name: laravel_nginx
        ports:
            - "9000:80"   # Внешний порт 9000 → внутренний порт 80
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    node:
        image: node:20
        container_name: laravel_node
        working_dir: /var/www/html
        volumes:
          - .:/var/www/html
        command: sh -c "npm install && npm run dev"

volumes:
    db_data:
